services:
  ssh-target:
    build: .
    container_name: ssh-target
    ports:
      - "2222:22"
    volumes:
      - ssh-host-keys:/etc/ssh
    networks:
      - soc-net

  attacker:
    build: ./attacker
    container_name: attacker
    networks:
      - soc-net
    tty: true
    stdin_open: true

networks:
  soc-net:
    driver: bridge

volumes:
  ssh-host-keys:
