services:
  ssh-target:
    build: .
    container_name: ssh-target
    cap_add:
      - NET_RAW
      - NET_ADMIN
    ports:
      - "2222:22"
    volumes:
      - ssh-host-keys:/etc/ssh
      - ./logs/ssh-target:/var/log
    networks:
      - soc-net

  attacker:
    build: ./attacker
    container_name: attacker
    networks:
      - soc-net
    tty: true
    stdin_open: true

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=soc
      - POSTGRES_PASSWORD=socpassword
      - POSTGRES_DB=soc
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - soc-net

  web-target:
    image: nginx:alpine
    container_name: web-target
    ports:
      - "8080:80"
    volumes:
      - ./logs/web-target:/var/log/nginx
    networks:
      - soc-net

networks:
  soc-net:
    driver: bridge

volumes:
  ssh-host-keys:
  pg-data:
